name: AoC 2025

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby 3.4.7
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Test with Rake
        run: bundle exec rake test